### PR TITLE
Upgrade Python version

### PR DESCRIPTION
**Pull request by seanh**

### CODE REVIEW

**Comment by seanh** [comment]
This doesn't seem to have upgraded the Python version in `Dockerfile`, not sure why

**Comment by marcospri** [comment]
> This doesn't seem to have upgraded the Python version in Dockerfile, not sure why

Should we upgrade it manually? The dockerfile is the actual version we use

**Review by marcospri — APPROVED** [review]

**Comment by seanh** [comment]
> > This doesn't seem to have upgraded the Python version in Dockerfile, not sure why
> 
> Should we upgrade it manually? The dockerfile is the actual version we use

Ah, this is deliberate. The cookiecutter never updates `Dockerfile` after initially generating it: <https://github.com/hypothesis/cookiecutters/blob/ecb494d473ac90a346c72ab50a8b1c9408e7192f/_shared/hooks/post_gen_project.py#L157>. It makes sense because we use Dependabot to update the version numbers in the `Dockerfile`, so if the cookiecutter updated `Dockerfile` it'd constantly be undoing Dependabot's changes.

I'll upgrade it manually

**Comment by seanh** [comment]
For some reason this project's `Dockerfile` was also stuck on Alpine 3.16 (the latest is 3.20). Dependabot hadn't been updating the project's Alpine version. Not sure why

**Pull request merged**
